version: 0.2

phases:
  install:
    commands:
      - echo Entering the install phase...
      - gem install cfn-nag
  build:
    commands:
      - echo Entering the build phase...
      - cfn_nag_scan --input-path $CODEBUILD_SRC_DIR
