AWSTemplateFormatVersion: "2010-09-09"
Description: Template to create a CodePipeline using a GitHub repository

Parameters:
  GitHubToken:
    Type: String
    Description: "GitHub OAuth Token for accessing the repository"
  GitHubOwner:
    Type: String
    Default: "your-github-username"
    Description: "The GitHub username or organization that owns the repository"
  GitHubRepo:
    Type: String
    Default: "your-repository-name"
    Description: "The name of the GitHub repository"
  GitHubBranch:
    Type: String
    Default: "main"
    Description: "The branch in the GitHub repository to track"
  PipelineName:
    Type: String
    Default: "AutomatoonzPipeline"
    Description: "The name of the pipeline"

Resources:
  # CodePipeline for GitHub integration
  MyPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref PipelineName
      RoleArn: arn:
